annotate_spec.js

Fix global variable leaks

---

Overview.html
Overview.src.html

Only set state to unsent when true

---

xhr.bs

Tests: https://github.com/w3c/web-platform-tests/pull/4614.

Reset response for abort() during DONE

---

.pr-preview.json
README.md
xhr.bs

See https://github.com/whatwg/meta/issues/16.

Meta: enable PR preview

---

xhr.bs

Tests: https://github.com/w3c/web-platform-tests/issues/4996.
Fixes #101.
***
[Preview](https://xhr.spec.whatwg.org/branch-snapshots/annevk/loadstart/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/xhr/d618835...24f81be.html)

Account for loadstart being able to change state

---

xhr.bs

See https://github.com/whatwg/infra/pull/156.
***
[Preview](https://xhr.spec.whatwg.org/branch-snapshots/annevk/json/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/xhr/1a8f691...9d5388a.html)

Use Infra for JSON parsing

---

xhr.bs

***
[Preview](https://xhr.spec.whatwg.org/branch-snapshots/annevk/export-entries/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/xhr/ed83926...fb5d571.html)

Meta: export FormData's concepts

---

LICENSE
xhr.bs

***
<a href="https://whatpr.org/xhr/184.html" title="Last updated on Jan 4, 2018, 6:14 PM GMT (fcdfb72)">Preview</a> | <a href="https://whatpr.org/xhr/184/97a30b4...fcdfb72.html" title="Last updated on Jan 4, 2018, 6:14 PM GMT (fcdfb72)">Diff</a>

Meta: use new WHATWG boilerplate and license

---

CONTRIBUTING.md
README.md

Helps with https://github.com/whatwg/meta/issues/65.

Meta: reference whatwg/meta resources

---

xhr.bs

Fixes #173.
***
<a href="https://whatpr.org/xhr/195.html" title="Last updated on Apr 10, 2018, 2:35 PM GMT (cb86579)">Preview</a> | <a href="https://whatpr.org/xhr/195/67a423f...cb86579.html" title="Last updated on Apr 10, 2018, 2:35 PM GMT (cb86579)">Diff</a>

Editorial: cleanup exception terminology

---

xhr.bs

***
<a href="https://whatpr.org/xhr/198.html" title="Last updated on Apr 11, 2018, 2:35 PM GMT (87a7bf5)">Preview</a> | <a href="https://whatpr.org/xhr/198/4b7915e...87a7bf5.html" title="Last updated on Apr 11, 2018, 2:35 PM GMT (87a7bf5)">Diff</a>

Editorial: use Infra for FormData

---

xhr.bs

Closes #197.
***
<a href="https://whatpr.org/xhr/205.html" title="Last updated on Apr 23, 2018, 2:56 PM GMT (4ed7d1c)">Preview</a> | <a href="https://whatpr.org/xhr/205/f759e3d...4ed7d1c.html" title="Last updated on Apr 23, 2018, 2:56 PM GMT (4ed7d1c)">Diff</a>

Editorial: rewrite send()'s body/content-type processing

---

xhr.bs

***
<a href="https://whatpr.org/xhr/214.html" title="Last updated on Jun 14, 2018, 12:17 PM GMT (4ef3b03)">Preview</a> | <a href="https://whatpr.org/xhr/214/9f22aa3...4ef3b03.html" title="Last updated on Jun 14, 2018, 12:17 PM GMT (4ef3b03)">Diff</a>

Reacting to timeout first. Fixes #212.

---

xhr.bs

It's bad practice these days per the Infra Standard and somewhat ambiguous at times.

Remove substep usage

---

xhr.bs

Tests: ...
Fixes #248.
***
<a href="https://whatpr.org/xhr/249.html" title="Last updated on May 23, 2019, 9:37 AM UTC (a2310bb)">Preview</a> | <a href="https://whatpr.org/xhr/249/27b769e...a2310bb.html" title="Last updated on May 23, 2019, 9:37 AM UTC (a2310bb)">Diff</a>

Change how getAllResponseHeaders() sorts

---

xhr.bs

See https://github.com/heycam/webidl/pull/750.
***
<a href="https://whatpr.org/xhr/250.html" title="Last updated on Aug 9, 2019, 8:24 AM UTC (fdd642b)">Preview</a> | <a href="https://whatpr.org/xhr/250/985f2f7...fdd642b.html" title="Last updated on Aug 9, 2019, 8:24 AM UTC (fdd642b)">Diff</a>

Align with IDL dictionary changes

---

xhr.bs

***
<a href="https://whatpr.org/xhr/269.html" title="Last updated on Apr 1, 2020, 9:04 AM UTC (dbe2d49)">Preview</a> | <a href="https://whatpr.org/xhr/269/90aa563...dbe2d49.html" title="Last updated on Apr 1, 2020, 9:04 AM UTC (dbe2d49)">Diff</a>

Editorial: use Infra for string to scalar value string conversion

---

xhr.bs

Follows https://github.com/whatwg/streams/pull/1073.
***
<a href="https://whatpr.org/xhr/292.html" title="Last updated on Sep 29, 2020, 4:57 PM UTC (aebcaa2)">Preview</a> | <a href="https://whatpr.org/xhr/292/59eb1d9...aebcaa2.html" title="Last updated on Sep 29, 2020, 4:57 PM UTC (aebcaa2)">Diff</a>

Use new Streams algorithms

---

xhr.bs

***
<a href="https://whatpr.org/xhr/291.html" title="Last updated on Sep 30, 2020, 8:45 AM UTC (a327138)">Preview</a> | <a href="https://whatpr.org/xhr/291/767b8fd...a327138.html" title="Last updated on Sep 30, 2020, 8:45 AM UTC (a327138)">Diff</a>

Meta: link Review Draft

---

xhr.bs

I hope this makes no normative changes, but it does make some major changes in how things are structured as a result of having to rewrite text anyway to ensure everything has the appropriate objects to work on.
***
<a href="https://whatpr.org/xhr/285.html" title="Last updated on Sep 30, 2020, 9:06 AM UTC (80275e6)">Preview</a> | <a href="https://whatpr.org/xhr/285/64f56c5...80275e6.html" title="Last updated on Sep 30, 2020, 9:06 AM UTC (80275e6)">Diff</a>

Editorial: modernize XMLHttpRequest

---

xhr.bs

Companion to whatwg/html#7371.
***
<a href="https://whatpr.org/xhr/338.html" title="Last updated on Nov 30, 2021, 8:55 AM UTC (e571c51)">Preview</a> | <a href="https://whatpr.org/xhr/338/88a61d5...e571c51.html" title="Last updated on Nov 30, 2021, 8:55 AM UTC (e571c51)">Diff</a>

Editorial: Use HTML's definitions of "entry list" and "entry"

---

xhr.bs

Fetch PR: https://github.com/whatwg/fetch/pull/1541.
(Skipped the template as that's covered by Fetch.)
***
<a href="https://whatpr.org/xhr/362.html" title="Last updated on Nov 21, 2022, 12:47 PM UTC (e86b94b)">Preview</a> | <a href="https://whatpr.org/xhr/362/545cdd5...e86b94b.html" title="Last updated on Nov 21, 2022, 12:47 PM UTC (e86b94b)">Diff</a>

Align with Fetch's forbidden request-header refactor

---

xhr.bs

Closes #380.
***
<a href="https://whatpr.org/xhr/382.html" title="Last updated on Sep 22, 2023, 7:04 AM UTC (f3a54f4)">Preview</a> | <a href="https://whatpr.org/xhr/382/1cccb46...f3a54f4.html" title="Last updated on Sep 22, 2023, 7:04 AM UTC (f3a54f4)">Diff</a>

Editorial: use HTML's encoding-parse a URL

---

xhr.bs

***
<a href="https://whatpr.org/xhr/401.html" title="Last updated on Aug 12, 2025, 1:31 PM UTC (648c18c)">Preview</a> | <a href="https://whatpr.org/xhr/401/f284317...648c18c.html" title="Last updated on Aug 12, 2025, 1:31 PM UTC (648c18c)">Diff</a>

Meta: link to Korean translations
