whatwg/xhr

Overview.html, Overview.src.html
As Fetch spec now uses ReadableStream instead of byte stream, XHR should follow it.
Fixes #57.
=> Replace byte stream with ReadableStream

Overview.html, Overview.src.html
Unfortunately all browsers but Firefox failed to implement the
standard. This does not change the fact that synchronous XMLHttpRequest
is deprecated.
Fixes #66.
=> Allow synchronous withCredentials

Overview.html, Overview.src.html
Use an operation defined in the fetch spec instead.
This change fixes #85.
=> Fix an obsolete ReadableStream operation name

Overview.html, Overview.src.html
Fire the final progress event before switching the state to DONE in
“handle response-end-of-body”. And no longer fire events named progress
in “request error steps”.
Fixes #72.
(This commit also removes the same-origin data-URL flag that is about
to be removed in Fetch per https://github.com/whatwg/fetch/issues/381.
That change has no impact on implementations.)
=> Fiddle with progress events

.editorconfig, .gitattributes, xhr.bs
Not sure if you want to add the terms index too, but I was looking for the IDL index and noticed it was missing, so here's a drive-by fix.
=> Editorial: add an IDL index

xhr.bs
They only run when new bytes are transmitted.
Closes #118.
***
[Preview](https://xhr.spec.whatwg.org/branch-snapshots/annevk/subsubsubsteps/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/xhr/7fb5717..annevk/subsubsubsteps:56821b2.html)
=> Clarify when subsubsubsteps run in "process response"

xhr.bs
Regressed in 01da69fb27d10a3315f9bf8259cc7074713379ee.
Fixes #116.
=> Regression fix: need transmitted/length defined before progress event dispatch

xhr.bs
As the objects are all mutually exclusive it makes no sense to store
and clear them separately.
Fixes #124.
***
[Preview](https://xhr.spec.whatwg.org/branch-snapshots/annevk/response-object/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/xhr/96e3512..annevk/response-object:8428ef2.html)
=> Editorial: use a single response object

xhr.bs
Implementations vary quite significantly in how they deal with invalid
input though (or lack of input).
Tests: https://github.com/w3c/web-platform-tests/pull/4955 and
https://github.com/w3c/web-platform-tests/pull/4993.
Fixes #82.
***
[Preview](https://xhr.spec.whatwg.org/branch-snapshots/annevk/overridemimetype/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/xhr/d618835..annevk/overridemimetype:e1988b2.html)
=> overrideMimeType does not throw for invalid input

xhr.bs
Fixes https://www.w3.org/Bugs/Public/show_bug.cgi?id=23632.
***
[Preview](https://xhr.spec.whatwg.org/branch-snapshots/annevk/content-type/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/xhr/e8ddc47...b80c10e.html)
=> Define MIME type extraction better

xhr.bs
In particular make use of new the new “contains” concept for header
lists and also use “byte-case-insensitive”. Also rename Content-Type as
variable to the far clearer mimeType.
***
[Preview](https://xhr.spec.whatwg.org/branch-snapshots/annevk/send-content-type-logic/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/xhr/13f033b...854bea6.html)
=> Define send()'s Content-Type logic in terms of Fetch

xhr.bs
In particular, setRequestHeader() should use 0x2C 0x20 as separator (not just 0x2C) and get(All)ResponseHeader(s)() should do so too. The latter also always needs to end in 0x0D 0x0A rather than omitting it at the end.
This depends on whatwg/fetch#504 landing first.
Tests: w3c/web-platform-tests#4641 and w3c/web-platform-tests#5008.
Fixes #108 and fixes #109.
***
[Preview](https://xhr.spec.whatwg.org/branch-snapshots/annevk/response-headers/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/xhr/0a7025a...184dc4f.html)
=> Align header handling with Fetch

xhr.bs
Fixes #112.
***
[Preview](https://xhr.spec.whatwg.org/branch-snapshots/annevk/timeout/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/xhr/a6e7981...237a19c.html)
=> Improve the wording around handling timeouts

xhr.bs
Also add highlighting for code. Fixes #136.
***
[Preview](https://xhr.spec.whatwg.org/branch-snapshots/annevk/examples/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/xhr/59c9cd9...2a2090b.html)
=> Sort and lowercase header names in getAllResponseHeaders() example

xhr.bs
***
[Preview](https://xhr.spec.whatwg.org/branch-snapshots/sideshowbarker/event-listeners-preflight-note/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/xhr/990a157...7f68460.html)
=> Add note about event listeners causing preflight

xhr.bs
***
[Preview](https://s3.amazonaws.com/pr-preview/jakearchibald/xhr/fetch-abort.html) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/xhr/7e332a5...jakearchibald:bbe3e77.html)
=> Updating to fit with fetch aborting

xhr.bs
***
[Preview](https://xhr.spec.whatwg.org/branch-snapshots/sideshowbarker/credentials-reference/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/xhr/1937a2e...cd26607.html)
=> Reference Fetch spec for “credentials” definition

xhr.bs
Fixes #160.
***
<a href="https://whatpr.org/xhr/171.html" title="Last updated on Dec 4, 2017, 1:06 PM GMT (aa50220)">Preview</a> | <a href="https://whatpr.org/xhr/171/900f013...aa50220.html" title="Last updated on Dec 4, 2017, 1:06 PM GMT (aa50220)">Diff</a>
=> Editorial: use HTML/XML MIME type terms

xhr.bs
Unfortunately forcing UTF-8 is not web compatible.
This also cleans up some other steps in the open() method in the process.
Tests: https://hg.mozilla.org/releases/mozilla-beta/rev/fd6134823ff9.
Fixes #159.
***
<a href="https://whatpr.org/xhr/172.html" title="Last updated on Dec 4, 2017, 1:18 PM GMT (6ee39d9)">Preview</a> | <a href="https://whatpr.org/xhr/172/900f013...6ee39d9.html" title="Last updated on Dec 4, 2017, 1:18 PM GMT (6ee39d9)">Diff</a>
=> Use the API URL character encoding for XMLHttpRequest

CONTRIBUTING.md, README.md, xhr.bs
Also fix a couple other nits.
***
<a href="https://whatpr.org/xhr/187.html" title="Last updated on Jan 12, 2018, 8:59 PM GMT (d62a11f)">Preview</a> | <a href="https://whatpr.org/xhr/187/74415d4...d62a11f.html" title="Last updated on Jan 12, 2018, 8:59 PM GMT (d62a11f)">Diff</a>
=> Meta: remove mention of CC0

xhr.bs
Note that this also replaces "utf-8" with "UTF-8" and no longer preserves duplicate parameters.
Tests: https://github.com/w3c/web-platform-tests/pull/8422.
***
<a href="https://whatpr.org/xhr/176.html" title="Last updated on Apr 10, 2018, 2:56 PM GMT (a85a8e9)">Preview</a> | <a href="https://whatpr.org/xhr/176/c6583e9...a85a8e9.html" title="Last updated on Apr 10, 2018, 2:56 PM GMT (a85a8e9)">Diff</a>
=> Define Content-Type manipulation in terms of MIME Sniffing

xhr.bs
Reset override MIME type when open() is invoked.
Actually make overriding the charset parameter work (setting override MIME type to the "MIME type portion" (now essence) as done previously would always erase it.
Tests: https://github.com/w3c/web-platform-tests/pull/8449.
***
<a href="https://whatpr.org/xhr/174.html" title="Last updated on Apr 16, 2018, 9:55 AM GMT (80dcbba)">Preview</a> | <a href="https://whatpr.org/xhr/174/edc6f8f...80dcbba.html" title="Last updated on Apr 16, 2018, 9:55 AM GMT (80dcbba)">Diff</a>
=> Fix overrideMimeType() again

xhr.bs
It's part of XMLHttpRequest, not ProgressEvent.
Fixes #199.
***
<a href="https://whatpr.org/xhr/204.html" title="Last updated on Apr 23, 2018, 4:47 PM GMT (ee158ca)">Preview</a> | <a href="https://whatpr.org/xhr/204/f759e3d...ee158ca.html" title="Last updated on Apr 23, 2018, 4:47 PM GMT (ee158ca)">Diff</a>
=> Editorial: move feature policy integration section

xhr.bs
This fixes https://github.com/whatwg/html/issues/3648.
***
<a href="https://whatpr.org/xhr/206.html" title="Last updated on May 1, 2018, 5:31 AM GMT (12d3587)">Preview</a> | <a href="https://whatpr.org/xhr/206/02600c4...12d3587.html" title="Last updated on May 1, 2018, 5:31 AM GMT (12d3587)">Diff</a>
=> Remove 'type' mapping for 'entry'.

xhr.bs
Only fire a "progress" event during "handle response end-of-body" for
asynchronous XHR. This matches existing browser behaviour.
Test at https://github.com/w3c/web-platform-tests/pull/10887.
Closes #207.
***
<a href="https://whatpr.org/xhr/208.html" title="Last updated on May 8, 2018, 10:17 AM GMT (8173703)">Preview</a> | <a href="https://whatpr.org/xhr/208/0b0dce1...8173703.html" title="Last updated on May 8, 2018, 10:17 AM GMT (8173703)">Diff</a>
=> Don't fire "progress" event for sync XHR

xhr.bs
A tiny and first pull request for https://github.com/whatwg/xhr/issues/213
:)
***
<a href="https://whatpr.org/xhr/215.html" title="Last updated on Jun 15, 2018, 7:53 AM GMT (c2f6eea)">Preview</a> | <a href="https://whatpr.org/xhr/215/9f22aa3...c2f6eea.html" title="Last updated on Jun 15, 2018, 7:53 AM GMT (c2f6eea)">Diff</a>
=> Remove outdated note from setRequestHeader()

xhr.bs
It does not make much sense as overrideMimeType() isn't blocked from being used before open() is invoked. (And 3/4 of the major implementations do not have this behavior.)
Partially reverts 121cee50b6f51215f046266642964b4c53a02a7c.
Tests: https://github.com/web-platform-tests/wpt/pull/12404.
Closes https://github.com/web-platform-tests/wpt/issues/12289.
***
<a href="https://whatpr.org/xhr/218.html" title="Last updated on Aug 10, 2018, 9:57 AM GMT (e288c10)">Preview</a> | <a href="https://whatpr.org/xhr/218/ce716e8...e288c10.html" title="Last updated on Aug 10, 2018, 9:57 AM GMT (e288c10)">Diff</a>
=> Do not reset override MIME type

xhr.bs
This will help web compatibility and address all cases linked from https://github.com/whatwg/mimesniff/issues/84.
Tests: ...
***
<a href="https://whatpr.org/xhr/224.html" title="Last updated on Oct 16, 2018, 1:20 PM GMT (0624970)">Preview</a> | <a href="https://whatpr.org/xhr/224/7d8526b...0624970.html" title="Last updated on Oct 16, 2018, 1:20 PM GMT (0624970)">Diff</a>
=> Limit Content-Type overrides to when charset isn't already UTF-8

xhr.bs
Header list's get is much nicer.
See https://github.com/whatwg/fetch/pull/840 for context.
***
<a href="https://whatpr.org/xhr/229.html" title="Last updated on Nov 27, 2018, 2:18 PM GMT (b4e8507)">Preview</a> | <a href="https://whatpr.org/xhr/229/721f3c9...b4e8507.html" title="Last updated on Nov 27, 2018, 2:18 PM GMT (b4e8507)">Diff</a>
=> Stop using "combined value"

xhr.bs
This aligns with the changes made in https://github.com/whatwg/fetch/pull/831. Fortunately the remainder of the prose already assumed it got a MIME type record rather than bytes.
***
<a href="https://whatpr.org/xhr/227.html" title="Last updated on Nov 13, 2018, 1:04 PM GMT (18924f9)">Preview</a> | <a href="https://whatpr.org/xhr/227/721f3c9...18924f9.html" title="Last updated on Nov 13, 2018, 1:04 PM GMT (18924f9)">Diff</a>
=> Extract a MIME type no longer returns bytes

xhr.bs
"teh" was intentional, but consistent tooling wins the day.
See https://github.com/whatwg/whatwg.org/pull/252 for context.
***
<a href="https://whatpr.org/xhr/247.html" title="Last updated on May 14, 2019, 9:56 AM UTC (fd3c628)">Preview</a> | <a href="https://whatpr.org/xhr/247/fef8ebc...fd3c628.html" title="Last updated on May 14, 2019, 9:56 AM UTC (fd3c628)">Diff</a>
=> Editorial: address lint nits

xhr.bs
Following-up on https://github.com/whatwg/fetch/pull/1029.
FIX #277
Mozilla cc @annevk
Google cc @yutakahirano
* There are various tests asserting for example that a locked or disturbed stream results in `send` throwing an error, so with this change the stream will be stringified so then I assume the `USVString` branch of https://fetch.spec.whatwg.org/#concept-bodyinit-extract will be hit, and `send` will not throw if the stream was locked or disturbed, so those tests will have to be re-written. I can do it as part of https://github.com/servo/servo/issues/26723
* Chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=1091120
* Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1643243
* Safari: https://bugs.webkit.org/show_bug.cgi?id=212731
(See [WHATWG Working Mode: …
=> Use XMLHttpRequestBodyInit as defined in Fetch, in send.

xhr.bs
See https://github.com/whatwg/fetch/pull/1165 for context.
@domenic so it seems XHR does all the awkward ways of reading a response body without helper. Lots of technical debt came with the introduction of streams to fetch. I didn't try to touch that here and instead focused purely on adopting the new callback approach, which does seem a lot cleaner in terms of what things get to run concurrently and such, but that does seem like an obvious thing to try to tackle next.
***
<a href="https://whatpr.org/xhr/311.html" title="Last updated on Feb 15, 2021, 6:36 AM UTC (0afb2ba)">Preview</a> | <a href="https://whatpr.org/xhr/311/8088cc5...0afb2ba.html" title="Last updated on Feb 15, 2021, 6:36 AM UTC (0afb2ba)">Diff</a>
=> Editorial: adopt Fetch's new approach to callbacks

xhr.bs
This fails the build because the Fetch change hasn't landed yet.
***
<a href="https://whatpr.org/xhr/313.html" title="Last updated on Feb 19, 2021, 4:07 PM UTC (f938b52)">Preview</a> | <a href="https://whatpr.org/xhr/313/cf10989...f938b52.html" title="Last updated on Feb 19, 2021, 4:07 PM UTC (f938b52)">Diff</a>
=> Use Fetch's body read algorithms

xhr.bs
And also clean up the way we manage XMLHttpRequest's response, which allows for simplifying "handle response end-of-body" and "handle errors".
Tests: https://github.com/web-platform-tests/wpt/pull/27778.
Fixes #314.
* Chrome (presumably)
* Safari (presumably)
* See above.
* Chrome: N/A
* Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1695216
* Safari: N/A
(See [WHATWG Working Mode: Changes](https://whatwg.org/working-mode#changes) for more details.)
***
<a href="https://whatpr.org/xhr/315.html" title="Last updated on Mar 3, 2021, 8:32 AM UTC (d06f5c4)">Preview</a> | <a href="https://whatpr.org/xhr/315/26f974f...d06f5c4.html" title="Last updated on Mar 3, 2021, 8:32 AM UTC (d06f5c4)">Diff</a>
=> Handle errors in response bodies

xhr.bs
The only information browsers use for progress events for responses is the Content-Length header.
Align on that and only use body's length concept for uploads.
Tests: web-platform-tests/wpt#27837.
Fetch PRs: whatwg/fetch#1183 & whatwg/fetch#1184.
* See https://github.com/whatwg/fetch/pull/1184.
* See above.
* See https://github.com/whatwg/fetch/pull/1184.
(See [WHATWG Working Mode: Changes](https://whatwg.org/working-mode#changes) for more details.)
***
<a href="https://whatpr.org/xhr/317.html" title="Last updated on Mar 11, 2021, 11:34 AM UTC (7f29c9a)">Preview</a> | <a href="https://whatpr.org/xhr/317/231e282...7f29c9a.html" title="Last updated on Mar 11, 2021, 11:34 AM UTC (7f29c9a)">Diff</a>
=> Use extract a length from Fetch

xhr.bs
See https://github.com/whatwg/xhr/pull/321 and https://github.com/whatwg/xhr/pull/295
***
<a href="https://whatpr.org/xhr/322.html" title="Last updated on Mar 26, 2021, 8:16 AM UTC (ec82fb3)">Preview</a> | <a href="https://whatpr.org/xhr/322/82ff852...ec82fb3.html" title="Last updated on Mar 26, 2021, 8:16 AM UTC (ec82fb3)">Diff</a>
=> Drop the “Feature Policy integration” section

xhr.bs
See #338 and whatwg/html#7371.
***
<a href="https://whatpr.org/xhr/339.html" title="Last updated on Dec 1, 2021, 9:46 AM UTC (da90b38)">Preview</a> | <a href="https://whatpr.org/xhr/339/1dc9103...da90b38.html" title="Last updated on Dec 1, 2021, 9:46 AM UTC (da90b38)">Diff</a>
=> Editorial: Point the remaining entry list links to the HTML spec

xhr.bs
When response is a network error or body is fully read,
finalize and report the response.
Depends on https://github.com/whatwg/fetch/pull/1185
See:
https://github.com/w3c/resource-timing/pull/261
and https://github.com/w3c/resource-timing/issues/252
***
<a href="https://whatpr.org/xhr/319.html" title="Last updated on Dec 14, 2021, 7:52 AM UTC (0b6b341)">Preview</a> | <a href="https://whatpr.org/xhr/319/7647033...0b6b341.html" title="Last updated on Dec 14, 2021, 7:52 AM UTC (0b6b341)">Diff</a>
***
<a href="https://whatpr.org/xhr/319.html" title="Last updated on Feb 11, 2022, 12:44 PM UTC (37ebd4b)">Preview</a> | <a href="https://whatpr.org/xhr/319/7647033...37ebd4b.html" title="Last updated on Feb 11, 2022, 12:44 PM UTC (37ebd4b)">Diff</a>
=> Resource Timing integration

xhr.bs
See https://github.com/whatwg/fetch/pull/1439.
***
<a href="https://whatpr.org/xhr/349.html" title="Last updated on May 11, 2022, 12:39 PM UTC (75e7977)">Preview</a> | <a href="https://whatpr.org/xhr/349/9d481f8...75e7977.html" title="Last updated on May 11, 2022, 12:39 PM UTC (75e7977)">Diff</a>
=> Editorial: use fetch's new "body with type"

xhr.bs
Depends on https://github.com/whatwg/fetch/pull/1413
This clarifies that a resource timing entry is always for a
fetch and not for a request or response.
***
<a href="https://whatpr.org/xhr/347.html" title="Last updated on Aug 15, 2022, 7:35 AM UTC (f0c21bc)">Preview</a> | <a href="https://whatpr.org/xhr/347/9d481f8...f0c21bc.html" title="Last updated on Aug 15, 2022, 7:35 AM UTC (f0c21bc)">Diff</a>
=> Editorial: Refactor for auto-reporting timing from fetch

xhr.bs
Closes #262, I went with the approach outlined [here](https://github.com/whatwg/xhr/issues/262#issuecomment-548720848). Implementation/MDN issues have been filed, and some implementation-specific POCs have also been created ([chromium](https://chromium-review.googlesource.com/c/chromium/src/+/4189297), [gecko](https://phabricator.services.mozilla.com/D167576), and [jsdom](https://github.com/jsdom/jsdom/pull/3496)).
* Additional context in #262 and https://github.com/whatwg/html/issues/3195
* https://github.com/web-platform-tests/wpt/pull/37895
* Chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=1410542
* Gecko: https://phabricator.services.mozilla.com/D167576
* WebKit: https://bugs.webkit.org/show_bug.cgi?id=251220
(See [WHATWG Working Mode: …
=> Add optional submitter argument to FormData constructor

review-drafts/2024-02.bs, xhr.bs
The [February 2024 Review Draft](https://xhr.spec.whatwg.org/review-drafts/2024-02/) for this Workstream will be published shortly after merging this pull request.
Under the [WHATWG IPR Policy](https://whatwg.org/ipr-policy), Participants may, within 45 days after publication of a Review Draft, exclude certain Essential Patent Claims from the Review Draft Licensing Obligations. See the [IPR Policy](https://whatwg.org/ipr-policy) for details.
***
<a href="https://whatpr.org/xhr/386.html" title="Last updated on Feb 19, 2024, 6:52 PM UTC (6711fe4)">Preview</a> | <a href="https://whatpr.org/xhr/386/813e308...6711fe4.html" title="Last updated on Feb 19, 2024, 6:52 PM UTC (6711fe4)">Diff</a>
=> Review Draft Publication: February 2024

xhr.bs
As discovered in https://github.com/w3c/webref/issues/1216#issuecomment-2068997553
***
<a href="https://whatpr.org/xhr/389.html" title="Last updated on Jun 6, 2024, 11:02 AM UTC (68a29d4)">Preview</a> | <a href="https://whatpr.org/xhr/389/fdd619d...68a29d4.html" title="Last updated on Jun 6, 2024, 11:02 AM UTC (68a29d4)">Diff</a>
=> [META] Ajust dfn-for of events on XHREventTarget

xhr.bs
See https://github.com/whatwg/html/pull/10497 which fixes the algorithm definition to take a Document
***
<a href="https://whatpr.org/xhr/390.html" title="Last updated on Aug 12, 2024, 1:12 PM UTC (bbd013d)">Preview</a> | <a href="https://whatpr.org/xhr/390/fd438ec...bbd013d.html" title="Last updated on Aug 12, 2024, 1:12 PM UTC (bbd013d)">Diff</a>
=> Update link for fragment serialization algorithm

xhr.bs
This allows specifications to use ProgressEvents while not necessarily giving away the exact number of bytes, for example by using numbers between 0 and 1. See discussion in https://github.com/webmachinelearning/writing-assistance-apis/issues/15 for the concrete use case.
* Chromium is interested
* Per comments in this thread, WebKit and Gecko are supportive
* https://github.com/web-platform-tests/wpt/pull/50714
* Chromium: https://issues.chromium.org/issues/381969448
* Gecko: https://bugzilla.mozilla.org/show_bug.cgi?id=1943649
* WebKit: https://bugs.webkit.org/show_bug.cgi?id=288688
(See [WHATWG Working Mode: Changes](https://whatwg.org/working-mode#changes) for more details.)
---
I wanted to get this PR up to judge implementer interest. It would be a decent bit cleaner if we all agreed …
=> Allow doubles for ProgressEvent's loaded and total
